name: Qwack Excel Deploy

on:
  workflow_dispatch:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  job_1:
    name: Build, Zip and Store
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      name: Checkout Code
      with:
        submodules: 'true'

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Qwack.sln
      working-directory: './'

    - name: Restore DotNet
      run: dotnet restore
      working-directory: './'

    - name: Build and Publish Excel Add-in
      working-directory: './'
      run: |
        $version = Get-Content ./version.txt
        dotnet build Qwack.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile 
    
    - name: Zip deployment
      uses: vimtor/action-zip@v1
      with:
        files: ./clients/Qwack.Excel.Next/bin/Release/net6.0-windows
        dest: QwackExcel.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: QwackExcel.Next
        path: ./QwackExcel.zip

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: QwackExcel.Next
        artifacts: QwackExcel.zip